### ISSUE TITLE
Remove firebase secrets from drone

### ISSUE THREAD

**Issue by snickell** [code-dot-org/code-dot-org#59830]
Just removed references to these from `.drone.yml` in #59824 :
```
      FIREBASE_NAME:
        from_secret: FIREBASE_NAME
      FIREBASE_SECRET:
        from_secret: FIREBASE_SECRET
      FIREBASE_SHARED_SECRET:
        from_secret: FIREBASE_SHARED_SECRET
```

Should finish the job and remove them from drone itself.
