### ISSUE TITLE
Bundle install still needs AWS credentials despite override in locals.yml

### ISSUE THREAD

**Issue by jasperlafortune** [code-dot-org/code-dot-org#66039]
I'm attempting to set up my environment to be an outside contributor. I made is as far as bundle install before running into errors. It seems like installation is still looking for AWS credentials even though I overrode the local options.

When I run `bundle exec rake install:hooks` I get:
`Error retrieving instance profile credentials: Failed to open TCP connection to 169.254.169.254:80 (execution expired)
git config --local include.path ../.gitconfig
Finished install:hooks (less than a minute)`

Or when I run `bundle exec rake install` I get, amidst other messages:
`Aws::Sigv4::Errors::MissingCredentialsError: missing credentials, provide credentials with one of the following options:
   :access_key_id and :secret_access_key
   :credentials
   :credentials_provider`

SETUP.md says I need to override the AWS secrets (as an outside contributor), but in `locals.yml` I have:
`slack_bot_token: localoverride
pardot_private_key: localoverride
properties_encryption_key: ''`

This is on WSL Ubuntu 22. Happy to provide any other missing details. Thanks!

**Comment by cat5inthecradle** [comment]
Hello! This is definitely a tricky process. It's possible you're missing some other config values. Make sure your "locals.yml" includes all of these `localoverride` values,  per "locals.yml.default"

```
# Some items in config.yml.erb are resolved via `!Secret`, which retrieves from
# AWS Secrets Manager. These will be unavailable to external Contributors, but are
# also not necessary for basic local development. Override them here to avoid
# errors accessing Secrets Manager.
#slack_bot_token: localoverride
#pardot_private_key: localoverride
#openai_student_learning_api_key: localoverride
```

Are you missing `openai_student_learning_api_key`?

**Comment by jasperlafortune** [comment]
Hi, thanks so much for your response! I was missing `openai_student_learning_api_key` but I get the same errors when I uncomment that line.

**Comment by kmcnaught** [comment]
I'm having the same problem here. I've added as many overrides as I can guess at to config.yml:
``` yml
# Some items in config.yml.erb are resolved via `!Secret`, which retrieves from
# AWS Secrets Manager. These will be unavailable to external Contributors, but are
# also not necessary for basic local development. Override them here to avoid
# errors accessing Secrets Manager.
slack_bot_token: localoverride
pardot_private_key: localoverride
openai_student_learning_api_key: localoverride
openai_measures_of_learning_api_key: localoverride
openai_evaluate_rubric_api_key: localoverride
cloudfront_key_pair_id: localoverride
cloudfront_private_key: localoverride
google_gemini_student_learning_api_key: localoverride
```

... and I get the same issues as @jasperlafortune :
```
$ bundle exec rake install:hooks
Error retrieving instance profile credentials: Failed to open TCP connection to 169.254.169.254:80 (Connection timed out - user specified timeout)
git config --local include.path ../.gitconfig
Finished install:hooks (less than a minute)```
